### ISSUE TITLE
Conda file to set up environment

### ISSUE THREAD

**Issue by tombisho** [ccmim/GWAS_pipeline#2]
Hi, is it likely that a conda file will be available for this soon? If not, what is the best way to reproduce the environment?

Thanks

**Comment by rbonazzola** [comment]
Dear @tombisho, 
I have created a Dockerfile under `docker/` that you can use as a reference to build your environment.
Alternatively, you can pull my pre-built image from DockerHub: rbonazzola/gwas_pipeline.
I have updated the README to reflect these additions.
Hope this helps,
Rodrigo

**Comment by tombisho** [comment]
Thank you very much! I will give this a go.

**Comment by rbonazzola** [comment]
I'm closing this issue, but feel free to re-open if necessary.
